// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:AspNetCore.MVC.RESTful.Controllers.ResourceControllerBase`2.Mapper")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:AspNetCore.MVC.RESTful.Parameters.CommonResourceParameters._pageSize")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1307:The behavior of 'string.Replace(string, string?)' could vary based on the current user's locale settings. Replace this call in 'AspNetCore.MVC.RESTful.AutoMapper.AutoMapperConventionsChecker.CheckMappingsFor(string, System.Collections.Generic.List<(string, string)>, bool)' with a call to 'string.Replace(string, string?, System.StringComparison)'.", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.AutoMapper.AutoMapperConventionsChecker.CheckMappingsFor(System.String,System.Collections.Generic.List{System.},System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member CheckMappingsFor does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.AutoMapper.AutoMapperConventionsChecker.CheckMappingsFor(System.String,System.Collections.Generic.List{System.},System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member Filters does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.AutoMapper.AutoMapperConventionsChecker.Filters(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member Parameters does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.AutoMapper.AutoMapperConventionsChecker.Parameters(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member Search does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.AutoMapper.AutoMapperConventionsChecker.Search(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'IActionResult InvalidModelStateResponse.SetupInvalidModelStateResponse(ActionContext context)', validate parameter 'context' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.Configuration.InvalidModelStateResponse.SetupInvalidModelStateResponse(Microsoft.AspNetCore.Mvc.ActionContext)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.Configuration.StartupExtensions.ConfigureExceptionHandling(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IWebHostEnvironment)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'void ResourceControllerBase<TDto, TEntity>.AddPaginationMetadataHeader<T>(PagedList<T> data, IResourceUris urls)', validate parameter 'urls' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.Controllers.ResourceControllerBase`2.AddPaginationMetadataHeader``1(AspNetCore.MVC.RESTful.Helpers.PagedList{``0},AspNetCore.MVC.RESTful.Helpers.IResourceUris)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'ActionResult ResourceControllerBase<TDto, TEntity>.ResourcePatch<TUpdateDto>(Guid id, JsonPatchDocument<TUpdateDto> patchDocument)', validate parameter 'patchDocument' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.Controllers.ResourceControllerBase`2.ResourcePatch``1(System.Guid,Microsoft.AspNetCore.JsonPatch.JsonPatchDocument{``0})~Microsoft.AspNetCore.Mvc.ActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'PagedList<T> PagedList<T>.Create(IQueryable<T> source, PaginationParameters pages)', validate parameter 'pages' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.Helpers.PagedList`1.Create(System.Linq.IQueryable{`0},AspNetCore.MVC.RESTful.Parameters.PaginationParameters)~AspNetCore.MVC.RESTful.Helpers.PagedList`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.Helpers.PagedList`1.Create(System.Linq.IQueryable{`0},AspNetCore.MVC.RESTful.Parameters.PaginationParameters)~AspNetCore.MVC.RESTful.Helpers.PagedList`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.Helpers.PagedList`1.Create(System.Linq.IQueryable{`0},System.Int32,System.Int32)~AspNetCore.MVC.RESTful.Helpers.PagedList`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1307:The behavior of 'string.EndsWith(string)' could vary based on the current user's locale settings. Replace this call in 'AspNetCore.MVC.RESTful.Helpers.QueryableApplySortExtension.ApplySort<T>(System.Linq.IQueryable<T>, string, System.Collections.Generic.IDictionary<string, AspNetCore.MVC.RESTful.Parameters.OrderByPropertyMappingValue>)' with a call to 'string.EndsWith(string, System.StringComparison)'.", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.Helpers.QueryableApplySortExtension.ApplySort``1(System.Linq.IQueryable{``0},System.String,System.Collections.Generic.IDictionary{System.String,AspNetCore.MVC.RESTful.Parameters.OrderByPropertyMappingValue})~System.Linq.IQueryable{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'ResourceUriBuilder.ResourceUriBuilder(IPaginationMetadata pagination, CommonResourceParameters common, Func<object, string> urlBuilder)', validate parameter 'urlBuilder' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.Helpers.ResourceUriBuilder.#ctor(AspNetCore.MVC.RESTful.Helpers.IPaginationMetadata,AspNetCore.MVC.RESTful.Parameters.CommonResourceParameters,System.Func{System.Object,System.String})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1308:In method 'ClauseIsValid', replace the call to 'ToLowerInvariant' with 'ToUpperInvariant'.", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.Parameters.OrderByPropertyMappingService`2.ClauseIsValid(System.String)~System.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1307:The behavior of 'string.Equals(string?)' could vary based on the current user's locale settings. Replace this call in 'AspNetCore.MVC.RESTful.Parameters.OrderByPropertyMappingService<TDto, TEntity>.ClauseIsValid(string)' with a call to 'string.Equals(string?, System.StringComparison)'.", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.Parameters.OrderByPropertyMappingService`2.ClauseIsValid(System.String)~System.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1716:In virtual/interface member Query<T>.ApplyQuery(IQueryable<T>), rename parameter set so that it no longer conflicts with the reserved language keyword 'Set'. Using a reserved keyword as the name of a parameter on a virtual/interface member makes it harder for consumers in other languages to override/implement the member.", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.Parameters.Query`1.ApplyQuery(System.Linq.IQueryable{`0})~System.Linq.IQueryable{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1716:Rename virtual/interface member IResourceRepository<T>.Get(Query<T>, Query<T>, PaginationParameters, OrderByParameters, IDictionary<string, OrderByPropertyMappingValue>) so that it no longer conflicts with the reserved language keyword 'Get'. Using a reserved keyword as the name of a virtual/interface member makes it harder for consumers in other languages to override/implement the member.", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.Repositories.IResourceRepository`1.Get(AspNetCore.MVC.RESTful.Parameters.Query{`0},AspNetCore.MVC.RESTful.Parameters.Query{`0},AspNetCore.MVC.RESTful.Parameters.PaginationParameters,AspNetCore.MVC.RESTful.Parameters.OrderByParameters,System.Collections.Generic.IDictionary{System.String,AspNetCore.MVC.RESTful.Parameters.OrderByPropertyMappingValue})~AspNetCore.MVC.RESTful.Helpers.PagedList{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1716:Rename virtual/interface member IResourceRepository<T>.Get(Guid) so that it no longer conflicts with the reserved language keyword 'Get'. Using a reserved keyword as the name of a virtual/interface member makes it harder for consumers in other languages to override/implement the member.", Justification = "<Pending>", Scope = "member", Target = "~M:AspNetCore.MVC.RESTful.Repositories.IResourceRepository`1.Get(System.Guid)~`0")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1716:Rename virtual/interface member IResourceUris.Next so that it no longer conflicts with the reserved language keyword 'Next'. Using a reserved keyword as the name of a virtual/interface member makes it harder for consumers in other languages to override/implement the member.", Justification = "<Pending>", Scope = "member", Target = "~P:AspNetCore.MVC.RESTful.Helpers.IResourceUris.Next")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1710:Rename AspNetCore.MVC.RESTful.Helpers.PagedList<T> to end in 'Collection'.", Justification = "<Pending>", Scope = "type", Target = "~T:AspNetCore.MVC.RESTful.Helpers.PagedList`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1724:The type name Query conflicts in whole or in part with the namespace name 'Microsoft.EntityFrameworkCore.Query'. Change either name to eliminate the conflict.", Justification = "<Pending>", Scope = "type", Target = "~T:AspNetCore.MVC.RESTful.Parameters.Query`1")]